### ISSUE TITLE
TRACE in python

### ISSUE THREAD

**Issue by qid12** [songpeng/ml-2dqsar#4]
（请原谅我用中文>_<）
今天完成的工作：
1. 化合物信息的python读入：遇到的主要问题是consmi, consmiNS, smilesStripSalt用rdkit转换为分子时都有约1000个出错；初步检查了几个错误的分子，在pubmed都有记录但SMILES信息不同，应该可以把它们挑出来替换后再试；

2. 基于现在的148814个分子，绘制sequence similarity和pharmacological similarity图
![20170904220508](https://user-images.githubusercontent.com/8091588/30029795-3a0ade9a-91bd-11e7-8ec7-f56b1e3068bc.png)
GPCR family (397 proteins)
![20170904220743](https://user-images.githubusercontent.com/8091588/30029847-7b4c9aa6-91bd-11e7-8095-35f85c432ab6.png)
kinase family (440 proteins)
- 初步看来，和文章初稿里的结果差不多——GPCR家族能看到一定的common modularity，但kinase其实挺不好的...
- 另外，ion channel和nuclear receptor的蛋白信息，尤其是uniprot信息缺失，暂时未画图
- 再另，不知道morgan fingerprint是不是也需要平行画个图？

3. 我在process_chemicals.py中写了几个function可能会有用：
- get_protein_family_ligands：输入所需蛋白家族的名称和相关信息所在的文档名，输出一个文件夹，文件夹里以蛋白家族中single protein的名字命名的.sdf文件，里面包含化合物名称、结构、SMILES、分子量、logP、affinity的信息；
- get_MACCS_fingerprint：输入一个.sdf文件名，输出这个文件中所有分子的MACCSkey构成的numpy.matrix和相应的affinity向量（即训练模型要用的X和y；每行一个分子）
- get_Morgan_fingerprint同理

明天计划：
- [ ] GPCR家族的Ridge regression modeling和PLSRegression
- [ ] 补缺漏的分子和蛋白质信息？
- [x] 补morgan fingerprint的pharmacological similarity图？

**Comment by qid12** [comment]
1. 新的similarity图：
![default](https://user-images.githubusercontent.com/8091588/30067321-10245e5a-928d-11e7-8732-460f8f098e5f.png)
GPCR family: 从左到右 MACCS， MORGAN，Sequence
![default](https://user-images.githubusercontent.com/8091588/30067347-20758b9e-928d-11e7-80c1-5733d039ee57.png)
kinase family: 从左到右 MACCS， MORGAN，Sequence

**Comment by qid12** [comment]
2. Ridge模型初步：
Example1:
![default](https://user-images.githubusercontent.com/8091588/30067573-bfcffc38-928d-11e7-8395-f1e7c15ecff5.png)
左边两列：alpha vs. score（越接近1越好），蓝色是训练集(60%)，橙色是交叉验证集(20%)
右边两列：测试集(20%)的 真实值 vs. 预测值
上面一行是MACCS：alpha = 30, RMSE = 1.4193, correlation coef = 0.2988
下面一行是Morgan: alpha = 2, RMSE = 0.599, correlation coef = 0.34665

Example2:
![default](https://user-images.githubusercontent.com/8091588/30067771-509675e4-928e-11e7-9c14-f6d4b8c14926.png)
左边两列：alpha vs. score（越接近1越好），蓝色是训练集，橙色是交叉验证集
右边两列：测试集的 真实值 vs. 预测值
上面一行是MACCS：alpha = 30, RMSE = 0.6766, correlation coef = 0.4460
下面一行是Morgan: alpha = 30, RMSE = 0.674, correlation coef = 0.4473

**Comment by songpeng** [comment]
1. The content will be moved to Wiki.
2. The tasks to be done will be moved to Project.
